export type ProgramCategory = 'wellness' | 'legacy' | 'business' | 'relationships';

export interface GuidedProgram {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: ProgramCategory;
  duration: number; // in days
  prompts: string[];
}

export const programCategories: Record<ProgramCategory, { name: string; icon: string; description: string }> = {
  wellness: {
    name: 'Wellness & Growth',
    icon: '🌱',
    description: 'Personal development and mindfulness',
  },
  legacy: {
    name: 'My Story & Legacy',
    icon: '📖',
    description: 'Preserve memories and life stories',
  },
  business: {
    name: 'Business & Dreams',
    icon: '🚀',
    description: 'Plan, build, and achieve your goals',
  },
  relationships: {
    name: 'Relationships',
    icon: '❤️',
    description: 'Strengthen bonds with loved ones',
  },
};

export const guidedPrograms: GuidedProgram[] = [
  // ===== WELLNESS & GROWTH =====
  {
    id: 'gratitude-30',
    name: '30 Days of Gratitude',
    description: 'Cultivate an attitude of appreciation',
    icon: '🙏',
    color: 'bg-amber-50 border-amber-200',
    category: 'wellness',
    duration: 30,
    prompts: [
      "What's one thing you often take for granted but are grateful for?",
      "Write about someone who has positively impacted your life.",
      "What's a skill or ability you're thankful to have?",
      "Describe a place that brings you peace and comfort.",
      "What's a challenge you've overcome that you're now grateful for?",
      "Write about a recent small pleasure that made you smile.",
      "What's something in nature that fills you with wonder?",
      "Who in your life always makes you feel supported?",
      "What's a piece of technology you're grateful exists?",
      "Describe a memory that warms your heart.",
      "What's something about your body you appreciate?",
      "Write about a book, song, or movie that changed your perspective.",
      "What's a simple daily routine you're thankful for?",
      "Who's a stranger who once showed you unexpected kindness?",
      "What's something you have now that past-you would be thrilled about?",
      "Describe a lesson learned from a difficult experience.",
      "What's an opportunity you're grateful to have had?",
      "Write about a pet or animal that has brought joy to your life.",
      "What's something about where you live that you appreciate?",
      "Who's a teacher or mentor you're grateful for?",
      "What's a comfort food and the memories it brings?",
      "Describe a friendship that has stood the test of time.",
      "What's a cultural tradition you value?",
      "Write about a time when everything worked out better than expected.",
      "What's something you love about the current season?",
      "Who always believes in you, even when you doubt yourself?",
      "What's a freedom or right you're grateful to have?",
      "Describe your favorite part of your daily routine.",
      "What's something that made you laugh recently?",
      "Looking back, what three things are you most grateful for from this month?",
    ],
  },
  {
    id: 'self-discovery',
    name: 'Self-Discovery Journey',
    description: 'Explore who you really are',
    icon: '🔮',
    color: 'bg-purple-50 border-purple-200',
    category: 'wellness',
    duration: 30,
    prompts: [
      "What are five words that best describe who you are?",
      "What's your earliest memory? How do you think it shaped you?",
      "What are you most passionate about? When did this passion begin?",
      "Describe your perfect day from start to finish.",
      "What do you value most in relationships?",
      "What's a belief you held strongly that has changed over time?",
      "When do you feel most like yourself?",
      "What would you do if you knew you couldn't fail?",
      "What are your three greatest strengths?",
      "What's a weakness you're working to improve?",
      "How do you typically handle conflict?",
      "What does success mean to you?",
      "Describe a turning point in your life.",
      "What role does creativity play in your life?",
      "What are you most afraid of? Why?",
      "How do you recharge when you're feeling drained?",
      "What legacy do you want to leave behind?",
      "What brings you a sense of purpose?",
      "How has your definition of happiness evolved?",
      "What's something you wish others understood about you?",
      "What boundaries do you need to set or maintain?",
      "How do you express love and care for others?",
      "What childhood dream still resonates with you?",
      "What does your ideal future look like?",
      "How do you handle uncertainty?",
      "What's a part of yourself you've struggled to accept?",
      "What motivates you to keep going during hard times?",
      "How has your relationship with yourself changed over time?",
      "What would you tell your younger self?",
      "After this journey, what have you discovered about yourself?",
    ],
  },
  {
    id: 'mindfulness-21',
    name: '21 Days of Mindfulness',
    description: 'Develop present-moment awareness',
    icon: '🧘',
    color: 'bg-teal-50 border-teal-200',
    category: 'wellness',
    duration: 21,
    prompts: [
      "Describe this present moment using all five senses.",
      "What thoughts keep replaying in your mind? Observe them without judgment.",
      "Write about your breath. Notice its rhythm and depth.",
      "What emotions are you carrying right now? Where do you feel them in your body?",
      "Describe one ordinary activity you did today with full attention.",
      "What's one thing you noticed today that you usually overlook?",
      "Write about a moment when you felt truly present recently.",
      "What distracts you most often? How can you gently redirect your focus?",
      "Describe the space around you in detail right now.",
      "What thoughts are you letting go of today?",
      "Write about eating one meal mindfully. What did you notice?",
      "How does your body feel in this moment? Scan from head to toe.",
      "What sounds can you hear right now? Near and far?",
      "Describe a conversation you had with full presence.",
      "What patterns in your thinking have you noticed this week?",
      "Write about walking somewhere today. What did you observe?",
      "What are you grateful for in this exact moment?",
      "How has being more mindful affected your daily life?",
      "What emotions came up today? How did you respond to them?",
      "Describe a moment of stillness you experienced recently.",
      "Reflecting on these 21 days, how has your awareness changed?",
    ],
  },
  {
    id: 'confidence-14',
    name: '14 Days to Confidence',
    description: 'Build self-esteem and inner strength',
    icon: '💪',
    color: 'bg-rose-50 border-rose-200',
    category: 'wellness',
    duration: 14,
    prompts: [
      "Write about a time when you surprised yourself with your own capability.",
      "What are ten things you genuinely like about yourself?",
      "Describe a compliment you received that was hard to accept. Why?",
      "What's a fear you've conquered? How did you do it?",
      "Write a letter of encouragement to yourself.",
      "What negative self-talk do you want to replace? With what?",
      "Describe a moment when you stood up for yourself.",
      "What accomplishment are you most proud of?",
      "Write about someone who inspires confidence in you.",
      "What would you attempt if you were confident enough?",
      "How do you handle criticism? How would you like to handle it?",
      "Describe your strengths as if you were recommending yourself for something.",
      "What's one small step you can take today to build confidence?",
      "Looking back on these two weeks, how has your self-perception changed?",
    ],
  },

  // ===== MY STORY & LEGACY =====
  {
    id: 'my-life-story',
    name: 'My Life Story',
    description: 'Chronicle your journey from childhood to now',
    icon: '📖',
    color: 'bg-amber-50 border-amber-300',
    category: 'legacy',
    duration: 30,
    prompts: [
      "Describe the home you grew up in. What did it look like, smell like, feel like?",
      "What's your earliest childhood memory? Describe it in vivid detail.",
      "Who were the most influential people in your early childhood?",
      "What games did you love to play as a child? Who did you play with?",
      "Describe a typical family dinner from your childhood.",
      "What were your favorite books, shows, or movies growing up?",
      "Write about your best friend from childhood. What adventures did you share?",
      "What was school like for you? What subjects did you love or struggle with?",
      "Describe a holiday tradition that was special to your family.",
      "What's a lesson you learned the hard way as a teenager?",
      "Who was your first crush? What do you remember about that feeling?",
      "What did you dream of becoming when you grew up?",
      "Describe a pivotal moment that changed the direction of your life.",
      "What's the bravest thing you've ever done?",
      "Write about meeting someone who changed your life forever.",
      "What's your proudest achievement? How did you accomplish it?",
      "Describe a time you failed and what you learned from it.",
      "What places have you lived? Which felt most like home?",
      "Write about a trip or adventure that shaped who you are.",
      "What's the hardest decision you've ever had to make?",
      "Describe a moment of pure joy in your adult life.",
      "What traditions have you created or carried on?",
      "Write about someone you've lost and what they meant to you.",
      "What are you most grateful for in your life right now?",
      "What wisdom would you share with your younger self?",
      "What do you hope people remember about you?",
      "Describe your life philosophy in your own words.",
      "What dreams do you still want to pursue?",
      "Write a letter to someone you love, saying everything you want them to know.",
      "Looking at your whole life, what's the through-line? What has always mattered to you?",
    ],
  },
  {
    id: 'letters-to-loved-ones',
    name: 'Letters to Loved Ones',
    description: 'Write meaningful letters to the people who matter',
    icon: '💌',
    color: 'bg-pink-50 border-pink-300',
    category: 'legacy',
    duration: 14,
    prompts: [
      "Write a letter to your mother (or mother figure). What do you want her to know?",
      "Write a letter to your father (or father figure). Share your heart with him.",
      "Write a letter to your spouse or partner. What do they mean to you?",
      "Write a letter to your child (or future child). What hopes do you have for them?",
      "Write a letter to your sibling(s). What memories and feelings do you want to share?",
      "Write a letter to your grandparent(s). What did they teach you?",
      "Write a letter to your best friend. Why are they so important to you?",
      "Write a letter to a mentor or teacher who shaped you.",
      "Write a letter to someone you've lost. What would you say to them now?",
      "Write a letter to someone you need to forgive (or seek forgiveness from).",
      "Write a letter to your younger self at a difficult time in your life.",
      "Write a letter to your future self, 10 years from now.",
      "Write a letter to someone who doesn't know how much they impacted you.",
      "Write a letter to the person you most want to thank.",
    ],
  },
  {
    id: 'family-history',
    name: 'Family History Project',
    description: 'Document your family stories for future generations',
    icon: '🌳',
    color: 'bg-green-50 border-green-300',
    category: 'legacy',
    duration: 21,
    prompts: [
      "Where did your family come from? What do you know about your ancestry?",
      "Write about your grandparents. What were their lives like?",
      "What family stories have been passed down through generations?",
      "Describe your parents' love story. How did they meet?",
      "What were your parents like as young adults?",
      "What hardships did your family overcome?",
      "What values were most important in your family growing up?",
      "Describe a family member who lived an extraordinary life.",
      "What family recipes have been passed down? What memories do they hold?",
      "Write about your family's immigration or migration story.",
      "What traditions make your family unique?",
      "Describe your family's faith or spiritual background.",
      "What did your parents teach you about work and money?",
      "Write about a family secret or little-known story.",
      "What historical events did your family live through?",
      "Describe the homes your parents and grandparents lived in.",
      "What family heirlooms or photos tell important stories?",
      "Write about a family reunion or gathering that stands out.",
      "What lessons from your family do you want to pass on?",
      "How has your family changed over the generations?",
      "What do you want future generations to know about your family?",
    ],
  },

  // ===== BUSINESS & DREAMS =====
  {
    id: 'business-builder',
    name: 'Business Builder',
    description: 'Plan and develop your business idea',
    icon: '💼',
    color: 'bg-blue-50 border-blue-300',
    category: 'business',
    duration: 21,
    prompts: [
      "What problem does your business solve? Why does this matter to you?",
      "Who is your ideal customer? Describe them in detail.",
      "What makes your solution unique? What's your competitive advantage?",
      "Write your business vision. Where do you see this in 5 years?",
      "What are your core values? How will they guide your business decisions?",
      "Describe your product or service in detail. What's the experience?",
      "Who are your competitors? What can you learn from them?",
      "What's your pricing strategy? How did you decide on this?",
      "How will customers find you? Describe your marketing approach.",
      "What are your startup costs? Make a realistic budget.",
      "What skills do you have? What skills do you need to develop or hire?",
      "What's your minimum viable product? How will you test your idea?",
      "What does success look like in Year 1? Set specific goals.",
      "What are the biggest risks? How will you mitigate them?",
      "Who do you need on your team? Describe your ideal collaborators.",
      "What technology or tools will you need?",
      "How will you fund your business? Explore your options.",
      "What's your sales process? How will you close deals?",
      "How will you measure progress? What metrics matter most?",
      "What could cause your business to fail? Be honest.",
      "Write your 30-second elevator pitch. Make it compelling.",
    ],
  },
  {
    id: 'dream-life-blueprint',
    name: 'Dream Life Blueprint',
    description: 'Design and plan your ideal future',
    icon: '✨',
    color: 'bg-indigo-50 border-indigo-300',
    category: 'business',
    duration: 21,
    prompts: [
      "If you had no limitations, what would your ideal life look like?",
      "Describe your perfect average day, 5 years from now.",
      "Where do you want to live? Describe your ideal home and location.",
      "What work would you do if money wasn't a factor?",
      "What does financial freedom mean to you? What's your number?",
      "Describe your ideal relationships and social life.",
      "What adventures and experiences are on your bucket list?",
      "How do you want to feel each day? What emotions do you want to experience?",
      "What impact do you want to have on others or the world?",
      "What hobbies and interests do you want to pursue?",
      "Describe your ideal health and fitness level.",
      "What would you need to let go of to achieve your dream life?",
      "What skills would you need to develop?",
      "Who do you need to become to live this life?",
      "What's one thing you could start doing today toward this vision?",
      "What limiting beliefs are holding you back?",
      "What does your support system look like in your dream life?",
      "How will you handle setbacks on the way to your dreams?",
      "Break your dream life into 1-year, 3-year, and 5-year goals.",
      "What daily habits will get you closer to your dreams?",
      "Write a letter from your future self who's living the dream.",
    ],
  },
  {
    id: 'goal-crusher',
    name: '30-Day Goal Crusher',
    description: 'Achieve a meaningful goal in 30 days',
    icon: '🎯',
    color: 'bg-orange-50 border-orange-300',
    category: 'business',
    duration: 30,
    prompts: [
      "What's one meaningful goal you want to achieve in the next 30 days?",
      "Why does this goal matter to you? Connect it to your deeper values.",
      "What will life look like when you achieve this goal?",
      "Break your goal into weekly milestones. What's Week 1?",
      "What obstacles might get in your way? List them honestly.",
      "For each obstacle, write a strategy to overcome it.",
      "Who can support you in this goal? How will you ask for help?",
      "What's the first small action you can take today?",
      "Day 8 check-in: What progress have you made? What adjustments needed?",
      "What's working well? Do more of it.",
      "What's not working? What will you change?",
      "Celebrate a small win from this week. You earned it.",
      "What's your Week 2 milestone? Are you on track?",
      "Write about a moment of doubt. How did you push through?",
      "Day 15 halfway check: Rate your progress 1-10. What would make it a 10?",
      "What have you learned about yourself during this challenge?",
      "Is your goal still the right goal? Adjust if needed.",
      "What's your Week 3 milestone? Push through the messy middle.",
      "Describe a breakthrough moment or key insight.",
      "How has pursuing this goal affected other areas of your life?",
      "What would you tell someone starting the same goal?",
      "Day 22: One week left. What's your final push plan?",
      "What will you do differently in the last week?",
      "Visualize completing your goal. How does it feel?",
      "Day 25 check-in: What's left to do?",
      "Write about the effort you've put in. Honor your work.",
      "What unexpected lessons have you learned?",
      "Day 28: Reflect on who you've become through this process.",
      "Day 29: Prepare for completion. What's your next goal?",
      "Day 30: Celebrate! Write about your achievement and key takeaways.",
    ],
  },

  // ===== RELATIONSHIPS =====
  {
    id: 'marriage-journal',
    name: 'Marriage & Partnership',
    description: 'Strengthen your bond and grow together',
    icon: '💑',
    color: 'bg-red-50 border-red-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      "What first attracted you to your partner? Relive those early feelings.",
      "Describe your favorite memory together. What made it special?",
      "What do you admire most about your partner?",
      "How has your relationship helped you grow as a person?",
      "What's a challenge you've overcome together? How did it strengthen you?",
      "What does your partner do that makes you feel loved?",
      "How do you show love to your partner? Is it in their love language?",
      "What dreams do you share for your future together?",
      "Describe a time your partner surprised you in a good way.",
      "What's something you've never told your partner but should?",
      "How do you handle conflict? What could improve?",
      "What daily rituals or habits strengthen your bond?",
      "Write about a time you felt truly seen by your partner.",
      "What do you wish your partner understood better about you?",
      "How do you maintain intimacy and connection?",
      "What's a fun adventure you want to share with your partner?",
      "How do you support each other's individual goals?",
      "What's the best advice about relationships you've received?",
      "Write a love letter to your partner. Say what's in your heart.",
      "What do you want your relationship to look like in 10 years?",
      "What three things will you do this week to invest in your relationship?",
    ],
  },
  {
    id: 'parenting-reflections',
    name: 'Parenting Reflections',
    description: 'Document your journey as a parent',
    icon: '👨‍👩‍👧‍👦',
    color: 'bg-sky-50 border-sky-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      "Describe the moment you first became a parent. What did you feel?",
      "What kind of parent do you want to be? What values do you want to instill?",
      "Write about a recent moment with your child that filled you with joy.",
      "What's the hardest part of parenting for you? How do you cope?",
      "Describe your child's personality. What makes them unique?",
      "What do you hope your child remembers about their childhood?",
      "How has being a parent changed you?",
      "Write about a parenting mistake and what you learned from it.",
      "What traditions are you creating with your children?",
      "How do you balance discipline with warmth?",
      "What's something your child has taught you?",
      "Describe a typical day with your family. What moments matter?",
      "How do you handle your child's big emotions?",
      "What do you want to do differently than your own parents?",
      "What do you want to carry forward from how you were raised?",
      "Write a letter to your child about who they are right now.",
      "What are your hopes and dreams for your child's future?",
      "How do you take care of yourself as a parent?",
      "What does your child need from you right now?",
      "Describe a moment when you felt like you got parenting right.",
      "What do you want your child to know about how much you love them?",
    ],
  },
  {
    id: 'healing-relationships',
    name: 'Healing Relationships',
    description: 'Process and heal relationship wounds',
    icon: '🩹',
    color: 'bg-violet-50 border-violet-300',
    category: 'relationships',
    duration: 14,
    prompts: [
      "What relationship in your life needs healing? Describe the situation.",
      "How has this relationship affected you emotionally?",
      "What's your role in what happened? Be honest with yourself.",
      "What hurt you most? Write it out fully.",
      "What do you wish the other person understood about you?",
      "Have you communicated your feelings clearly? What held you back?",
      "What would an apology from them look like? What would you need to hear?",
      "Is there anything you need to apologize for?",
      "What boundaries do you need to set?",
      "What would forgiveness look like? Is it possible?",
      "How would healing this relationship change your life?",
      "What's one step you could take toward reconciliation or closure?",
      "Write a letter you may never send, saying everything you need to say.",
      "What will you carry forward? What will you release?",
    ],
  },
  {
    id: 'friendship-circle',
    name: 'Friendship Circle',
    description: 'Celebrate and nurture your friendships',
    icon: '🤝',
    color: 'bg-cyan-50 border-cyan-300',
    category: 'relationships',
    duration: 14,
    prompts: [
      "Who are the most important friends in your life? What makes each special?",
      "Describe your oldest friendship. How has it evolved over time?",
      "What do you look for in a friend? What qualities matter most?",
      "Write about a friend who showed up for you when you needed it most.",
      "How do you show up for your friends? Are you the friend you want to be?",
      "Is there a friendship you've let fade that you miss?",
      "What's the best advice a friend has ever given you?",
      "Describe a favorite memory with friends. What made it special?",
      "How do you make new friends at this stage of life?",
      "What boundaries are important in your friendships?",
      "Write a thank you letter to a friend who has made a difference.",
      "How do you navigate when friendships change or end?",
      "What kind of friend do you want to be going forward?",
      "Plan something intentional for a friendship this week. What will you do?",
    ],
  },
];

// Get program progress from localStorage
export function getProgramProgress(programId: string): { startDate: string | null; currentDay: number } {
  if (typeof window === 'undefined') {
    return { startDate: null, currentDay: 0 };
  }

  const key = `program_${programId}`;
  const stored = localStorage.getItem(key);

  if (!stored) {
    return { startDate: null, currentDay: 0 };
  }

  const { startDate } = JSON.parse(stored);
  const start = new Date(startDate);
  const now = new Date();
  const diffTime = Math.abs(now.getTime() - start.getTime());
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

  return { startDate, currentDay: diffDays + 1 };
}

// Start a program
export function startProgram(programId: string): void {
  if (typeof window === 'undefined') return;

  const key = `program_${programId}`;
  localStorage.setItem(key, JSON.stringify({
    startDate: new Date().toISOString(),
  }));
}

// Reset a program
export function resetProgram(programId: string): void {
  if (typeof window === 'undefined') return;

  const key = `program_${programId}`;
  localStorage.removeItem(key);
}

// Get programs by category
export function getProgramsByCategory(category: ProgramCategory): GuidedProgram[] {
  return guidedPrograms.filter(p => p.category === category);
}
