export type ProgramCategory = 'wellness' | 'legacy' | 'business' | 'relationships' | 'creativity';

export interface GuidedProgram {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: ProgramCategory;
  duration: number; // in days
  prompts: string[];
}

export const programCategories: Record<ProgramCategory, { name: string; icon: string; description: string }> = {
  wellness: {
    name: 'Wellness & Growth',
    icon: '🌱',
    description: 'Personal development and mindfulness',
  },
  legacy: {
    name: 'My Story & Legacy',
    icon: '📖',
    description: 'Preserve memories and life stories',
  },
  business: {
    name: 'Business & Dreams',
    icon: '🚀',
    description: 'Plan, build, and achieve your goals',
  },
  relationships: {
    name: 'Relationships',
    icon: '❤️',
    description: 'Strengthen bonds with loved ones',
  },
  creativity: {
    name: 'Creativity & Expression',
    icon: '🎨',
    description: 'Unlock your creative potential',
  },
};

export const guidedPrograms: GuidedProgram[] = [
  // ===== WELLNESS & GROWTH =====
  {
    id: 'gratitude-30',
    name: '30 Days of Gratitude',
    description: 'Cultivate an attitude of appreciation',
    icon: '🙏',
    color: 'bg-amber-50 border-amber-200',
    category: 'wellness',
    duration: 30,
    prompts: [
      "What's one thing you often take for granted but are grateful for?",
      "Write about someone who has positively impacted your life.",
      "What's a skill or ability you're thankful to have?",
      "Describe a place that brings you peace and comfort.",
      "What's a challenge you've overcome that you're now grateful for?",
      "Write about a recent small pleasure that made you smile.",
      "What's something in nature that fills you with wonder?",
      "Who in your life always makes you feel supported?",
      "What's a piece of technology you're grateful exists?",
      "Describe a memory that warms your heart.",
      "What's something about your body you appreciate?",
      "Write about a book, song, or movie that changed your perspective.",
      "What's a simple daily routine you're thankful for?",
      "Who's a stranger who once showed you unexpected kindness?",
      "What's something you have now that past-you would be thrilled about?",
      "Describe a lesson learned from a difficult experience.",
      "What's an opportunity you're grateful to have had?",
      "Write about a pet or animal that has brought joy to your life.",
      "What's something about where you live that you appreciate?",
      "Who's a teacher or mentor you're grateful for?",
      "What's a comfort food and the memories it brings?",
      "Describe a friendship that has stood the test of time.",
      "What's a cultural tradition you value?",
      "Write about a time when everything worked out better than expected.",
      "What's something you love about the current season?",
      "Who always believes in you, even when you doubt yourself?",
      "What's a freedom or right you're grateful to have?",
      "Describe your favorite part of your daily routine.",
      "What's something that made you laugh recently?",
      "Looking back, what three things are you most grateful for from this month?",
    ],
  },
  {
    id: 'self-discovery',
    name: 'Self-Discovery Journey',
    description: 'Explore who you really are',
    icon: '🔮',
    color: 'bg-purple-50 border-purple-200',
    category: 'wellness',
    duration: 30,
    prompts: [
      "What are five words that best describe who you are?",
      "What's your earliest memory? How do you think it shaped you?",
      "What are you most passionate about? When did this passion begin?",
      "Describe your perfect day from start to finish.",
      "What do you value most in relationships?",
      "What's a belief you held strongly that has changed over time?",
      "When do you feel most like yourself?",
      "What would you do if you knew you couldn't fail?",
      "What are your three greatest strengths?",
      "What's a weakness you're working to improve?",
      "How do you typically handle conflict?",
      "What does success mean to you?",
      "Describe a turning point in your life.",
      "What role does creativity play in your life?",
      "What are you most afraid of? Why?",
      "How do you recharge when you're feeling drained?",
      "What legacy do you want to leave behind?",
      "What brings you a sense of purpose?",
      "How has your definition of happiness evolved?",
      "What's something you wish others understood about you?",
      "What boundaries do you need to set or maintain?",
      "How do you express love and care for others?",
      "What childhood dream still resonates with you?",
      "What does your ideal future look like?",
      "How do you handle uncertainty?",
      "What's a part of yourself you've struggled to accept?",
      "What motivates you to keep going during hard times?",
      "How has your relationship with yourself changed over time?",
      "What would you tell your younger self?",
      "After this journey, what have you discovered about yourself?",
    ],
  },
  {
    id: 'mindfulness-21',
    name: '21 Days of Mindfulness',
    description: 'Develop present-moment awareness',
    icon: '🧘',
    color: 'bg-teal-50 border-teal-200',
    category: 'wellness',
    duration: 21,
    prompts: [
      "Describe this present moment using all five senses.",
      "What thoughts keep replaying in your mind? Observe them without judgment.",
      "Write about your breath. Notice its rhythm and depth.",
      "What emotions are you carrying right now? Where do you feel them in your body?",
      "Describe one ordinary activity you did today with full attention.",
      "What's one thing you noticed today that you usually overlook?",
      "Write about a moment when you felt truly present recently.",
      "What distracts you most often? How can you gently redirect your focus?",
      "Describe the space around you in detail right now.",
      "What thoughts are you letting go of today?",
      "Write about eating one meal mindfully. What did you notice?",
      "How does your body feel in this moment? Scan from head to toe.",
      "What sounds can you hear right now? Near and far?",
      "Describe a conversation you had with full presence.",
      "What patterns in your thinking have you noticed this week?",
      "Write about walking somewhere today. What did you observe?",
      "What are you grateful for in this exact moment?",
      "How has being more mindful affected your daily life?",
      "What emotions came up today? How did you respond to them?",
      "Describe a moment of stillness you experienced recently.",
      "Reflecting on these 21 days, how has your awareness changed?",
    ],
  },
  {
    id: 'confidence-14',
    name: '14 Days to Confidence',
    description: 'Build self-esteem and inner strength',
    icon: '💪',
    color: 'bg-rose-50 border-rose-200',
    category: 'wellness',
    duration: 14,
    prompts: [
      "Write about a time when you surprised yourself with your own capability.",
      "What are ten things you genuinely like about yourself?",
      "Describe a compliment you received that was hard to accept. Why?",
      "What's a fear you've conquered? How did you do it?",
      "Write a letter of encouragement to yourself.",
      "What negative self-talk do you want to replace? With what?",
      "Describe a moment when you stood up for yourself.",
      "What accomplishment are you most proud of?",
      "Write about someone who inspires confidence in you.",
      "What would you attempt if you were confident enough?",
      "How do you handle criticism? How would you like to handle it?",
      "Describe your strengths as if you were recommending yourself for something.",
      "What's one small step you can take today to build confidence?",
      "Looking back on these two weeks, how has your self-perception changed?",
    ],
  },

  // ===== MY STORY & LEGACY =====
  {
    id: 'my-life-story',
    name: 'My Life Story',
    description: 'Chronicle your journey from childhood to now',
    icon: '📖',
    color: 'bg-amber-50 border-amber-300',
    category: 'legacy',
    duration: 30,
    prompts: [
      "Describe the home you grew up in. What did it look like, smell like, feel like?",
      "What's your earliest childhood memory? Describe it in vivid detail.",
      "Who were the most influential people in your early childhood?",
      "What games did you love to play as a child? Who did you play with?",
      "Describe a typical family dinner from your childhood.",
      "What were your favorite books, shows, or movies growing up?",
      "Write about your best friend from childhood. What adventures did you share?",
      "What was school like for you? What subjects did you love or struggle with?",
      "Describe a holiday tradition that was special to your family.",
      "What's a lesson you learned the hard way as a teenager?",
      "Who was your first crush? What do you remember about that feeling?",
      "What did you dream of becoming when you grew up?",
      "Describe a pivotal moment that changed the direction of your life.",
      "What's the bravest thing you've ever done?",
      "Write about meeting someone who changed your life forever.",
      "What's your proudest achievement? How did you accomplish it?",
      "Describe a time you failed and what you learned from it.",
      "What places have you lived? Which felt most like home?",
      "Write about a trip or adventure that shaped who you are.",
      "What's the hardest decision you've ever had to make?",
      "Describe a moment of pure joy in your adult life.",
      "What traditions have you created or carried on?",
      "Write about someone you've lost and what they meant to you.",
      "What are you most grateful for in your life right now?",
      "What wisdom would you share with your younger self?",
      "What do you hope people remember about you?",
      "Describe your life philosophy in your own words.",
      "What dreams do you still want to pursue?",
      "Write a letter to someone you love, saying everything you want them to know.",
      "Looking at your whole life, what's the through-line? What has always mattered to you?",
    ],
  },
  {
    id: 'letters-to-loved-ones',
    name: 'Letters to Loved Ones',
    description: 'Write meaningful letters to the people who matter',
    icon: '💌',
    color: 'bg-pink-50 border-pink-300',
    category: 'legacy',
    duration: 14,
    prompts: [
      "Write a letter to your mother (or mother figure). What do you want her to know?",
      "Write a letter to your father (or father figure). Share your heart with him.",
      "Write a letter to your spouse or partner. What do they mean to you?",
      "Write a letter to your child (or future child). What hopes do you have for them?",
      "Write a letter to your sibling(s). What memories and feelings do you want to share?",
      "Write a letter to your grandparent(s). What did they teach you?",
      "Write a letter to your best friend. Why are they so important to you?",
      "Write a letter to a mentor or teacher who shaped you.",
      "Write a letter to someone you've lost. What would you say to them now?",
      "Write a letter to someone you need to forgive (or seek forgiveness from).",
      "Write a letter to your younger self at a difficult time in your life.",
      "Write a letter to your future self, 10 years from now.",
      "Write a letter to someone who doesn't know how much they impacted you.",
      "Write a letter to the person you most want to thank.",
    ],
  },
  {
    id: 'family-history',
    name: 'Family History Project',
    description: 'Document your family stories for future generations',
    icon: '🌳',
    color: 'bg-green-50 border-green-300',
    category: 'legacy',
    duration: 21,
    prompts: [
      "Where did your family come from? What do you know about your ancestry?",
      "Write about your grandparents. What were their lives like?",
      "What family stories have been passed down through generations?",
      "Describe your parents' love story. How did they meet?",
      "What were your parents like as young adults?",
      "What hardships did your family overcome?",
      "What values were most important in your family growing up?",
      "Describe a family member who lived an extraordinary life.",
      "What family recipes have been passed down? What memories do they hold?",
      "Write about your family's immigration or migration story.",
      "What traditions make your family unique?",
      "Describe your family's faith or spiritual background.",
      "What did your parents teach you about work and money?",
      "Write about a family secret or little-known story.",
      "What historical events did your family live through?",
      "Describe the homes your parents and grandparents lived in.",
      "What family heirlooms or photos tell important stories?",
      "Write about a family reunion or gathering that stands out.",
      "What lessons from your family do you want to pass on?",
      "How has your family changed over the generations?",
      "What do you want future generations to know about your family?",
    ],
  },

  // ===== BUSINESS & DREAMS =====
  {
    id: 'business-builder',
    name: 'Business Builder',
    description: 'Plan and develop your business idea',
    icon: '💼',
    color: 'bg-blue-50 border-blue-300',
    category: 'business',
    duration: 21,
    prompts: [
      "What problem does your business solve? Why does this matter to you?",
      "Who is your ideal customer? Describe them in detail.",
      "What makes your solution unique? What's your competitive advantage?",
      "Write your business vision. Where do you see this in 5 years?",
      "What are your core values? How will they guide your business decisions?",
      "Describe your product or service in detail. What's the experience?",
      "Who are your competitors? What can you learn from them?",
      "What's your pricing strategy? How did you decide on this?",
      "How will customers find you? Describe your marketing approach.",
      "What are your startup costs? Make a realistic budget.",
      "What skills do you have? What skills do you need to develop or hire?",
      "What's your minimum viable product? How will you test your idea?",
      "What does success look like in Year 1? Set specific goals.",
      "What are the biggest risks? How will you mitigate them?",
      "Who do you need on your team? Describe your ideal collaborators.",
      "What technology or tools will you need?",
      "How will you fund your business? Explore your options.",
      "What's your sales process? How will you close deals?",
      "How will you measure progress? What metrics matter most?",
      "What could cause your business to fail? Be honest.",
      "Write your 30-second elevator pitch. Make it compelling.",
    ],
  },
  {
    id: 'dream-life-blueprint',
    name: 'Dream Life Blueprint',
    description: 'Design and plan your ideal future',
    icon: '✨',
    color: 'bg-indigo-50 border-indigo-300',
    category: 'business',
    duration: 21,
    prompts: [
      "If you had no limitations, what would your ideal life look like?",
      "Describe your perfect average day, 5 years from now.",
      "Where do you want to live? Describe your ideal home and location.",
      "What work would you do if money wasn't a factor?",
      "What does financial freedom mean to you? What's your number?",
      "Describe your ideal relationships and social life.",
      "What adventures and experiences are on your bucket list?",
      "How do you want to feel each day? What emotions do you want to experience?",
      "What impact do you want to have on others or the world?",
      "What hobbies and interests do you want to pursue?",
      "Describe your ideal health and fitness level.",
      "What would you need to let go of to achieve your dream life?",
      "What skills would you need to develop?",
      "Who do you need to become to live this life?",
      "What's one thing you could start doing today toward this vision?",
      "What limiting beliefs are holding you back?",
      "What does your support system look like in your dream life?",
      "How will you handle setbacks on the way to your dreams?",
      "Break your dream life into 1-year, 3-year, and 5-year goals.",
      "What daily habits will get you closer to your dreams?",
      "Write a letter from your future self who's living the dream.",
    ],
  },
  {
    id: 'goal-crusher',
    name: '30-Day Goal Crusher',
    description: 'Achieve a meaningful goal in 30 days',
    icon: '🎯',
    color: 'bg-orange-50 border-orange-300',
    category: 'business',
    duration: 30,
    prompts: [
      "What's one meaningful goal you want to achieve in the next 30 days?",
      "Why does this goal matter to you? Connect it to your deeper values.",
      "What will life look like when you achieve this goal?",
      "Break your goal into weekly milestones. What's Week 1?",
      "What obstacles might get in your way? List them honestly.",
      "For each obstacle, write a strategy to overcome it.",
      "Who can support you in this goal? How will you ask for help?",
      "What's the first small action you can take today?",
      "Day 8 check-in: What progress have you made? What adjustments needed?",
      "What's working well? Do more of it.",
      "What's not working? What will you change?",
      "Celebrate a small win from this week. You earned it.",
      "What's your Week 2 milestone? Are you on track?",
      "Write about a moment of doubt. How did you push through?",
      "Day 15 halfway check: Rate your progress 1-10. What would make it a 10?",
      "What have you learned about yourself during this challenge?",
      "Is your goal still the right goal? Adjust if needed.",
      "What's your Week 3 milestone? Push through the messy middle.",
      "Describe a breakthrough moment or key insight.",
      "How has pursuing this goal affected other areas of your life?",
      "What would you tell someone starting the same goal?",
      "Day 22: One week left. What's your final push plan?",
      "What will you do differently in the last week?",
      "Visualize completing your goal. How does it feel?",
      "Day 25 check-in: What's left to do?",
      "Write about the effort you've put in. Honor your work.",
      "What unexpected lessons have you learned?",
      "Day 28: Reflect on who you've become through this process.",
      "Day 29: Prepare for completion. What's your next goal?",
      "Day 30: Celebrate! Write about your achievement and key takeaways.",
    ],
  },

  // ===== RELATIONSHIPS =====
  {
    id: 'marriage-journal',
    name: 'Marriage & Partnership',
    description: 'Strengthen your bond and grow together',
    icon: '💑',
    color: 'bg-red-50 border-red-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      "What first attracted you to your partner? Relive those early feelings.",
      "Describe your favorite memory together. What made it special?",
      "What do you admire most about your partner?",
      "How has your relationship helped you grow as a person?",
      "What's a challenge you've overcome together? How did it strengthen you?",
      "What does your partner do that makes you feel loved?",
      "How do you show love to your partner? Is it in their love language?",
      "What dreams do you share for your future together?",
      "Describe a time your partner surprised you in a good way.",
      "What's something you've never told your partner but should?",
      "How do you handle conflict? What could improve?",
      "What daily rituals or habits strengthen your bond?",
      "Write about a time you felt truly seen by your partner.",
      "What do you wish your partner understood better about you?",
      "How do you maintain intimacy and connection?",
      "What's a fun adventure you want to share with your partner?",
      "How do you support each other's individual goals?",
      "What's the best advice about relationships you've received?",
      "Write a love letter to your partner. Say what's in your heart.",
      "What do you want your relationship to look like in 10 years?",
      "What three things will you do this week to invest in your relationship?",
    ],
  },
  {
    id: 'parenting-reflections',
    name: 'Parenting Reflections',
    description: 'Document your journey as a parent',
    icon: '👨‍👩‍👧‍👦',
    color: 'bg-sky-50 border-sky-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      "Describe the moment you first became a parent. What did you feel?",
      "What kind of parent do you want to be? What values do you want to instill?",
      "Write about a recent moment with your child that filled you with joy.",
      "What's the hardest part of parenting for you? How do you cope?",
      "Describe your child's personality. What makes them unique?",
      "What do you hope your child remembers about their childhood?",
      "How has being a parent changed you?",
      "Write about a parenting mistake and what you learned from it.",
      "What traditions are you creating with your children?",
      "How do you balance discipline with warmth?",
      "What's something your child has taught you?",
      "Describe a typical day with your family. What moments matter?",
      "How do you handle your child's big emotions?",
      "What do you want to do differently than your own parents?",
      "What do you want to carry forward from how you were raised?",
      "Write a letter to your child about who they are right now.",
      "What are your hopes and dreams for your child's future?",
      "How do you take care of yourself as a parent?",
      "What does your child need from you right now?",
      "Describe a moment when you felt like you got parenting right.",
      "What do you want your child to know about how much you love them?",
    ],
  },
  {
    id: 'healing-relationships',
    name: 'Healing Relationships',
    description: 'Process and heal relationship wounds',
    icon: '🩹',
    color: 'bg-violet-50 border-violet-300',
    category: 'relationships',
    duration: 14,
    prompts: [
      "What relationship in your life needs healing? Describe the situation.",
      "How has this relationship affected you emotionally?",
      "What's your role in what happened? Be honest with yourself.",
      "What hurt you most? Write it out fully.",
      "What do you wish the other person understood about you?",
      "Have you communicated your feelings clearly? What held you back?",
      "What would an apology from them look like? What would you need to hear?",
      "Is there anything you need to apologize for?",
      "What boundaries do you need to set?",
      "What would forgiveness look like? Is it possible?",
      "How would healing this relationship change your life?",
      "What's one step you could take toward reconciliation or closure?",
      "Write a letter you may never send, saying everything you need to say.",
      "What will you carry forward? What will you release?",
    ],
  },
  {
    id: 'friendship-circle',
    name: 'Friendship Circle',
    description: 'Celebrate and nurture your friendships',
    icon: '🤝',
    color: 'bg-cyan-50 border-cyan-300',
    category: 'relationships',
    duration: 14,
    prompts: [
      "Who are the most important friends in your life? What makes each special?",
      "Describe your oldest friendship. How has it evolved over time?",
      "What do you look for in a friend? What qualities matter most?",
      "Write about a friend who showed up for you when you needed it most.",
      "How do you show up for your friends? Are you the friend you want to be?",
      "Is there a friendship you've let fade that you miss?",
      "What's the best advice a friend has ever given you?",
      "Describe a favorite memory with friends. What made it special?",
      "How do you make new friends at this stage of life?",
      "What boundaries are important in your friendships?",
      "Write a thank you letter to a friend who has made a difference.",
      "How do you navigate when friendships change or end?",
      "What kind of friend do you want to be going forward?",
      "Plan something intentional for a friendship this week. What will you do?",
    ],
  },
  {
    id: 'grief-and-loss',
    name: 'Grief & Loss',
    description: 'A gentle journey through loss and healing',
    icon: '🕊️',
    color: 'bg-slate-50 border-slate-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      // Week 1: Acknowledging the loss
      "Write about the person or thing you've lost. Who were they to you? What did they mean in your life?",
      "Describe a favorite memory that makes you smile, even through the tears.",
      "What were the little things about them that you loved? The habits, quirks, or small moments?",
      "Write about the day you learned of your loss. What do you remember feeling?",
      "What has been the hardest part of this loss? Allow yourself to be honest.",
      "Who has been there for you during this time? How have they helped?",
      "What does your grief feel like today? Where do you feel it in your body?",

      // Week 2: Processing emotions
      "Write a letter to the person you've lost. Say everything you wish you could tell them.",
      "What did this person teach you? What values or lessons do you carry forward?",
      "Describe a tradition, place, or song that reminds you of them. What memories does it hold?",
      "Are there things left unsaid? Write them here, even if they're difficult.",
      "What do you miss most about your life before this loss?",
      "Write about a time they made you laugh. What was their sense of humor like?",
      "How has this loss changed you? What parts of yourself feel different?",

      // Week 3: Finding meaning and moving forward
      "What would they want you to know right now? What would they say to comfort you?",
      "How do you want to honor their memory? What traditions might you create?",
      "Write about something beautiful you've witnessed since your loss—a moment of unexpected grace.",
      "What has grief taught you about love, about life, about yourself?",
      "Who else is grieving this loss? How might you support each other?",
      "What does moving forward look like for you? Moving forward doesn't mean forgetting.",
      "Write a final letter: What will you carry with you? What are you ready to release?",
    ],
  },

  // ===== NEW WELLNESS PROGRAMS =====
  {
    id: 'anxiety-toolkit',
    name: 'Anxiety Toolkit',
    description: 'Build strategies to manage anxious thoughts and feelings',
    icon: '🧠',
    color: 'bg-blue-50 border-blue-200',
    category: 'wellness',
    duration: 21,
    prompts: [
      // Week 1: Understanding your anxiety
      "Describe your anxiety. When does it show up? What does it feel like in your body?",
      "What are the situations or triggers that most often bring on anxious feelings?",
      "How has anxiety affected your daily life? What has it cost you?",
      "Write about your earliest memory of feeling anxious. What was happening?",
      "What thoughts typically run through your mind when you're anxious? List them without judgment.",
      "How do you currently cope with anxiety? What helps, even a little?",
      "What would your life look like if anxiety had less power over you?",

      // Week 2: Building coping strategies
      "Practice the 5-4-3-2-1 grounding technique right now. Describe 5 things you see, 4 you hear, 3 you feel, 2 you smell, 1 you taste.",
      "Write a letter to your anxious self from your calm, wise self. What comfort would you offer?",
      "What's a worry you've had that never came true? What does this teach you?",
      "Describe a time you felt anxious but pushed through anyway. What helped you cope?",
      "What physical activities help calm your nervous system? How can you do more of them?",
      "Write about someone who makes you feel safe and calm. What is it about them?",
      "What boundaries would help reduce anxiety in your life? With work? With people? With yourself?",

      // Week 3: Reframing and moving forward
      "Take an anxious thought and challenge it. What's the evidence for and against it?",
      "What would you attempt if you weren't afraid? Write about it in detail.",
      "How can you practice self-compassion when anxiety strikes? Write yourself a compassionate response.",
      "What small wins have you had with managing anxiety? Celebrate them here.",
      "Create a personalized anxiety toolkit: List 5-10 strategies that work for you.",
      "Write about how your relationship with anxiety has shifted during this program.",
      "What will you do differently going forward? What commitment will you make to yourself?",
    ],
  },
  {
    id: 'burnout-recovery',
    name: 'Burnout Recovery',
    description: 'Rebuild your energy, boundaries, and sense of purpose',
    icon: '🔥',
    color: 'bg-orange-50 border-orange-200',
    category: 'wellness',
    duration: 21,
    prompts: [
      // Week 1: Acknowledging burnout
      "Describe your current state of exhaustion. How does burnout show up in your body, mind, and emotions?",
      "What led you here? Trace the path—when did you start running on empty?",
      "What warning signs did you ignore? What were you telling yourself at the time?",
      "How has burnout affected your relationships, your work, your sense of self?",
      "What parts of your life feel most depleted right now? Rank them honestly.",
      "What have you been saying 'yes' to that you should have declined?",
      "Write about what you've sacrificed in the pursuit of productivity or achievement.",

      // Week 2: Creating space for recovery
      "What does rest actually look like for you? Not productive rest—real rest.",
      "What activities genuinely restore your energy? When did you last do them?",
      "Write about the boundaries you need to set. With work? With others? With yourself?",
      "What can you take off your plate right now? What can wait? What can you delegate or delete?",
      "Describe your ideal day if energy wasn't a constraint. What would you do?",
      "Who in your life drains you? Who fills you up? How can you adjust?",
      "What perfectionist tendencies contributed to your burnout? How can you soften them?",

      // Week 3: Rebuilding with intention
      "What matters most to you? Has burnout clarified your priorities?",
      "Redefine success for yourself. What does a sustainable, fulfilling life look like?",
      "What will you do differently this time? What non-negotiables will you protect?",
      "Write a permission slip to yourself. What are you allowing yourself to do or not do?",
      "How will you recognize early warning signs in the future? Create your personal burnout checklist.",
      "What brings you a sense of purpose without depleting you?",
      "Write a letter to your future self to read if you start burning out again. What do you need to remember?",
    ],
  },
  {
    id: 'self-compassion',
    name: 'Self-Compassion Practice',
    description: 'Replace self-criticism with kindness and understanding',
    icon: '💝',
    color: 'bg-pink-50 border-pink-200',
    category: 'wellness',
    duration: 14,
    prompts: [
      "How do you typically talk to yourself when you make a mistake? Write down your inner critic's voice.",
      "Now write to yourself about that same mistake as if you were talking to a dear friend. Notice the difference.",
      "What critical messages did you receive growing up? How do they still echo in your self-talk?",
      "Describe a current struggle you're facing. Acknowledge that struggle is part of being human.",
      "Write three kind things about yourself that have nothing to do with achievement or productivity.",
      "What do you need to hear right now? Write yourself the words you're longing for.",
      "Think of someone who loves you unconditionally. What would they say about your worthiness?",
      "What mistake or failure are you still punishing yourself for? Can you offer yourself forgiveness?",
      "Write about a physical part of yourself you've criticized. Can you thank your body instead?",
      "What are you grieving or struggling with that you haven't allowed yourself to fully feel?",
      "Create a self-compassion phrase you can use when you're suffering. Something like: 'This is hard. I'm doing my best.'",
      "How would your life change if you treated yourself with consistent kindness?",
      "Write a compassionate letter to your younger self who needed to hear these words.",
      "What commitment will you make to practicing self-compassion going forward?",
    ],
  },
  {
    id: 'morning-pages',
    name: 'Morning Pages',
    description: 'A daily stream-of-consciousness writing practice',
    icon: '🌅',
    color: 'bg-yellow-50 border-yellow-200',
    category: 'wellness',
    duration: 30,
    prompts: [
      "Write whatever comes to mind. Don't think, just write. Fill the page with your unfiltered thoughts.",
      "What's on your mind this morning? What did you dream about? How does your body feel?",
      "Let the pen move without stopping. Write about anything—worries, ideas, random observations, feelings.",
      "What's weighing on you today? Get it out of your head and onto the page.",
      "Write about what you see around you, then let your mind wander wherever it wants to go.",
      "No judgment, no editing. Just write continuously for the next few minutes.",
      "What would you do today if you had no obligations? Let your imagination flow.",
      "Write about something small that's been bothering you. Then write about something small that brings joy.",
      "Stream of consciousness: start with the word 'I' and don't stop writing until you fill the page.",
      "What's something you haven't told anyone? Write it here where no one will read it.",
      "Let your thoughts tumble out. Messy is fine. Boring is fine. Just keep writing.",
      "What are you avoiding? Write around it, through it, about it.",
      "Morning brain dump: what's cluttering your mental space right now?",
      "Write a conversation between two parts of yourself—the critic and the creator.",
      "What do you need today? What do you want? Let the answers emerge through writing.",
      "Free write about your current season of life. What's growing? What's ending?",
      "Write without punctuation or paragraphs. Let it be one continuous stream.",
      "What would you write if you knew no one would ever read it? Write that.",
      "Today's page is for complaints. Get them all out. Whine freely.",
      "Today's page is for gratitude. What's good? What's working? What do you appreciate?",
      "Write about time. How does it feel right now—fast, slow, heavy, light?",
      "What patterns do you notice in your morning pages so far? What keeps coming up?",
      "Write a letter that starts with 'Dear Life...'",
      "What are you curious about today? Follow the thread of curiosity on the page.",
      "Write about your relationship with writing itself. Has it changed during this practice?",
      "What wants to be expressed through you today? Let it come through.",
      "Write about the space between your thoughts. What lives in the silence?",
      "If your morning pages could talk back, what would they say to you?",
      "What have you discovered about yourself through this daily practice?",
      "Final morning pages: Reflect on 30 days of writing. What will you carry forward?",
    ],
  },
  {
    id: 'digital-detox',
    name: 'Digital Detox Diary',
    description: 'Build a healthier relationship with technology',
    icon: '📵',
    color: 'bg-emerald-50 border-emerald-200',
    category: 'wellness',
    duration: 14,
    prompts: [
      "Be honest: How much time did you spend on your phone yesterday? How did it make you feel?",
      "What apps or sites do you reach for compulsively? What triggers that reach?",
      "Describe a time before smartphones. What did you do with idle moments?",
      "What are you avoiding when you scroll? Boredom? Anxiety? Loneliness? Something else?",
      "Track your pickups today. Every time you reach for your phone, pause and write why.",
      "What would you do with an extra 2 hours a day if you weren't on screens?",
      "How has social media affected your self-image, your relationships, your mood?",
      "Spend 30 minutes doing something offline today. Write about how it felt.",
      "What notifications actually matter? Which ones are just noise? Consider turning some off.",
      "Write about the last time you felt truly present and undistracted. What were you doing?",
      "Design your ideal relationship with technology. What would balance look like?",
      "What boundaries will you set? No phone in bedroom? No scrolling before 9am? Define them.",
      "Spend an evening without screens. Tomorrow, write about what you noticed.",
      "What will you commit to going forward? Write your personal digital wellness plan.",
    ],
  },
  {
    id: 'sobriety-journal',
    name: 'Sobriety Journal',
    description: 'Daily support for your recovery journey',
    icon: '🌿',
    color: 'bg-green-50 border-green-200',
    category: 'wellness',
    duration: 30,
    prompts: [
      "Why are you choosing sobriety? Write your deepest reasons—the ones that will anchor you.",
      "What does your life look like when you're not sober? Be honest about the costs.",
      "Describe the life you're building in recovery. What becomes possible?",
      "What are your triggers? List the people, places, emotions, and situations that challenge you.",
      "For each trigger, write a coping strategy. What will you do instead?",
      "Who supports your sobriety? How can you lean on them more?",
      "Write about a craving you've successfully navigated. What helped you through?",
      "What emotions are hardest to feel without numbing? How can you process them differently?",
      "Day 8 check-in: How are you feeling? What's been harder than expected? Easier?",
      "Write a letter to your past self who was struggling. What do you want them to know?",
      "What healthy habits are replacing old patterns? Celebrate your new routines.",
      "Describe a moment of clarity or peace you've experienced in sobriety.",
      "What relationships have improved? Which ones are challenging? How are you navigating?",
      "Write about something you're proud of this week, no matter how small.",
      "Halfway point: Reflect on two weeks. What have you learned about yourself?",
      "What does self-care look like for you in recovery? List your go-to practices.",
      "Write about a difficult day. What made it hard? How did you get through?",
      "What amends, if any, do you want to make? Write about what healing might look like.",
      "How has your relationship with yourself changed since starting this journey?",
      "What activities bring you joy without substances? How can you do more of them?",
      "Day 21: Three weeks in. Write a gratitude list for your sober life.",
      "What fears do you still carry about recovery? Name them honestly.",
      "Write about who you're becoming. How is sobriety reshaping your identity?",
      "What would you tell someone just starting their sobriety journey?",
      "Describe your vision for one year of sobriety. What will be different?",
      "How do you handle social situations now? What strategies work for you?",
      "Write about a moment you felt truly present and alive in recovery.",
      "What has sobriety taught you about strength, vulnerability, and growth?",
      "Day 29: Tomorrow is day 30. How do you feel? What will you remember about this month?",
      "Day 30: Celebrate your milestone. Write a letter to your future self to read when it gets hard.",
    ],
  },

  // ===== NEW LEGACY PROGRAMS =====
  {
    id: 'my-career-story',
    name: 'My Career Story',
    description: 'Document your professional journey and lessons learned',
    icon: '💼',
    color: 'bg-slate-50 border-slate-300',
    category: 'legacy',
    duration: 21,
    prompts: [
      "What was your first job? What did you learn from it, even if it wasn't glamorous?",
      "What did you want to be when you grew up? How did that dream evolve?",
      "Who was your first mentor or boss who believed in you? What did they teach you?",
      "Describe a career failure or rejection that ultimately led somewhere better.",
      "What's the bravest professional decision you ever made?",
      "Write about a project or accomplishment you're genuinely proud of.",
      "What skills have you developed over your career? Which ones surprised you?",
      "Describe your most challenging boss or colleague. What did that relationship teach you?",
      "What career advice have you received that turned out to be wrong?",
      "What advice would you give to someone just starting in your field?",
      "Write about a time you had to reinvent yourself professionally.",
      "What does meaningful work look like to you? Has your definition changed?",
      "Describe a team or company culture where you thrived. What made it work?",
      "What risks did you take that paid off? Which ones didn't, and what did you learn?",
      "How have you balanced career ambition with other parts of life?",
      "Write about a professional relationship that shaped your career trajectory.",
      "What do you wish you'd known at the start of your career?",
      "What are you most proud of professionally that has nothing to do with titles or money?",
      "How has your industry or field changed during your career?",
      "What legacy do you want to leave through your work?",
      "Looking back at your entire career arc, what's the through-line? What has it all been about?",
    ],
  },
  {
    id: 'retirement-reflections',
    name: 'Retirement Reflections',
    description: 'Process this transition and design your next chapter',
    icon: '🌅',
    color: 'bg-amber-50 border-amber-300',
    category: 'legacy',
    duration: 21,
    prompts: [
      "How do you feel about retirement? Excited? Anxious? Relieved? All of the above?",
      "What did your work identity mean to you? How does it feel to shift away from it?",
      "Write about your last day of work or the moment you knew it was time.",
      "What will you miss most about working? What will you miss least?",
      "How will you introduce yourself now that you're not defined by your job?",
      "What did you sacrifice during your working years that you can now reclaim?",
      "Describe your ideal retired life. What does a perfect week look like?",
      "What have you always wanted to learn, explore, or try? Now's the time.",
      "How will you stay mentally engaged and challenged?",
      "What role will social connection play? How will you build community?",
      "Write about your relationship with your partner or family as you enter this phase together.",
      "What does purpose look like in retirement? Where will you find meaning?",
      "How do you want to spend your time, energy, and resources in this chapter?",
      "What adventures are on your retirement bucket list?",
      "How will you take care of your health in this new phase?",
      "What wisdom from your working life do you want to pass on?",
      "Write a letter to your retired self from five years ago. What would surprise them?",
      "What fears do you have about retirement? Name them and address them.",
      "How do you want to be remembered by former colleagues?",
      "What does financial peace look like in retirement? What's your relationship with money now?",
      "Write about the person you're becoming in retirement. Who are you now?",
    ],
  },
  {
    id: 'travel-memories',
    name: 'Travel Memories',
    description: 'Capture the places and journeys that shaped you',
    icon: '✈️',
    color: 'bg-sky-50 border-sky-300',
    category: 'legacy',
    duration: 14,
    prompts: [
      "What's your earliest travel memory? Where did your family take you?",
      "Describe a trip that changed your perspective on life.",
      "Write about a place that felt like a second home. What made it special?",
      "What's the most adventurous thing you've ever done while traveling?",
      "Describe a travel mishap that became a great story.",
      "Write about a person you met while traveling who left an impression.",
      "What destination is still on your bucket list? Why does it call to you?",
      "Describe your favorite meal in a foreign place. Set the scene.",
      "Write about a trip where everything went wrong but you still loved it.",
      "What have you learned about yourself through travel?",
      "Describe a landscape or view that took your breath away.",
      "Write about traveling with someone you love. What memories did you make?",
      "What place would you return to again and again? Why?",
      "If you could take one more trip anywhere in the world, where would you go and why?",
    ],
  },
  {
    id: 'recipes-and-traditions',
    name: 'Recipes & Traditions',
    description: 'Preserve the family recipes and stories behind them',
    icon: '🍲',
    color: 'bg-orange-50 border-orange-300',
    category: 'legacy',
    duration: 14,
    prompts: [
      "What's a recipe that's been in your family for generations? Write it down with the story behind it.",
      "Describe your grandmother's (or another elder's) kitchen. What smells and sounds do you remember?",
      "What was your favorite childhood meal? Who made it, and when did you eat it?",
      "Write about a holiday food tradition in your family. Why is it meaningful?",
      "What's a recipe you learned as an adult that has become part of your identity?",
      "Describe a meal that brings back a specific memory. Set the scene.",
      "What did food represent in your family growing up? Love? Scarcity? Celebration? Culture?",
      "Write about a family member who was an amazing cook. What made their food special?",
      "What food traditions have you created in your own family?",
      "Is there a recipe you regret not learning from someone before they passed? Write what you remember.",
      "Describe your perfect comfort food meal. What makes it comforting?",
      "What's a food from your heritage that connects you to your roots?",
      "Write a recipe as if you're teaching your grandchild to make it. Include the tips and stories.",
      "What food traditions do you hope will continue for generations? Why do they matter?",
    ],
  },

  // ===== NEW BUSINESS PROGRAMS =====
  {
    id: 'side-hustle-starter',
    name: 'Side Hustle Starter',
    description: 'Validate your idea and take the first steps',
    icon: '🌱',
    color: 'bg-lime-50 border-lime-300',
    category: 'business',
    duration: 14,
    prompts: [
      "What's the side hustle idea you can't stop thinking about? Describe it fully.",
      "Why this idea? What problem does it solve, and why are you the right person to solve it?",
      "Who would pay for this? Describe your ideal customer in detail.",
      "What's the simplest version of this you could offer? Think minimum viable product.",
      "What skills do you already have that apply? What would you need to learn?",
      "How many hours per week can you realistically dedicate to this?",
      "What's stopping you from starting? List your fears and obstacles honestly.",
      "For each obstacle, brainstorm one way to overcome or work around it.",
      "Who do you know that could be your first customer or could introduce you to one?",
      "What would you need to charge to make this worthwhile? Do the basic math.",
      "Research one competitor today. What can you learn from them? What would you do differently?",
      "What's one small action you could take this week to move forward?",
      "Visualize your side hustle one year from now, thriving. What does it look like?",
      "Commit: What will you do in the next 7 days to turn this idea into something real?",
    ],
  },
  {
    id: 'career-pivot',
    name: 'Career Pivot',
    description: 'Navigate your transition to meaningful new work',
    icon: '🔄',
    color: 'bg-indigo-50 border-indigo-300',
    category: 'business',
    duration: 21,
    prompts: [
      "What's driving your desire to change careers? Be completely honest.",
      "What parts of your current work do you want to leave behind?",
      "What parts of your current work would you want to carry forward?",
      "If money and practicality weren't factors, what would you do?",
      "What are your non-negotiables in a career? Flexibility? Purpose? Income? List and rank them.",
      "Write about a time you felt truly engaged and energized by work. What were you doing?",
      "What are you naturally good at that others often struggle with?",
      "What industries or fields intrigue you? Research one today and write about what you learned.",
      "Who do you know who has made a successful career pivot? What can you learn from them?",
      "What's the scariest part of making this change? Name your fears.",
      "What's the cost of staying where you are? Project forward five years if nothing changes.",
      "What skills gap exists between where you are and where you want to be?",
      "How could you start gaining experience in your new direction while still employed?",
      "What financial runway do you need? How long can you afford a transition period?",
      "Write your ideal job description for a role that doesn't exist yet.",
      "Who in your network could help with this pivot? How will you reach out?",
      "What story will you tell about your career change? Practice your narrative.",
      "What's one small experiment you can run to test your new direction?",
      "How will you handle doubt and discouragement during the transition?",
      "Write a letter from your future self who successfully made this pivot.",
      "What's your next step? Create a 30-60-90 day plan for your career pivot.",
    ],
  },
  {
    id: 'leadership-journal',
    name: 'Leadership Journal',
    description: 'Develop your leadership style and grow your impact',
    icon: '👑',
    color: 'bg-purple-50 border-purple-300',
    category: 'business',
    duration: 21,
    prompts: [
      "What kind of leader do you want to be? Describe your leadership vision.",
      "Who has been the best leader you've worked under? What made them effective?",
      "Who has been the worst? What did you learn about what not to do?",
      "What are your greatest strengths as a leader? How can you leverage them more?",
      "What leadership weaknesses do you need to work on? Be honest.",
      "Describe a difficult leadership decision you've had to make. How did you handle it?",
      "How do you handle conflict on your team? Is it effective?",
      "Write about a time you failed as a leader. What did you learn?",
      "How do you build trust with your team? What practices work?",
      "What's your communication style? How does it land with different people?",
      "How do you balance being liked with being respected?",
      "Write about someone on your team who challenges you. What can you learn from them?",
      "How do you develop and grow the people who report to you?",
      "What's your approach to giving feedback? Could it be more effective?",
      "How do you make decisions? What's your process?",
      "Write about a leadership situation you're currently navigating.",
      "How do you maintain your own energy and avoid burning out as a leader?",
      "What does servant leadership mean to you? How do you practice it?",
      "How do you lead through uncertainty and change?",
      "What legacy do you want to leave as a leader?",
      "Write a leadership credo—the principles you lead by.",
    ],
  },
  {
    id: 'money-mindset',
    name: 'Money Mindset',
    description: 'Transform your relationship with money',
    icon: '💰',
    color: 'bg-emerald-50 border-emerald-300',
    category: 'business',
    duration: 21,
    prompts: [
      "What messages about money did you receive growing up? From your family? From society?",
      "How do you feel when you think about money? Anxious? Excited? Ashamed? Empowered?",
      "What's your current relationship with money? Are you friends or enemies?",
      "What money mistakes have you made? What did they teach you?",
      "What limiting beliefs about money might be holding you back?",
      "Write about a time you felt abundant. What created that feeling?",
      "Write about a time you felt scarcity. What created that feeling?",
      "What does 'enough' look like for you? Define your enough number.",
      "How do you feel about earning money? Do you feel worthy of being well-paid?",
      "How do you feel about spending money? What do you spend freely on? What feels hard?",
      "What would you do if you had complete financial freedom?",
      "What money conversation have you been avoiding? With yourself? With a partner?",
      "Write about your relationship with debt. What emotions come up?",
      "What does generosity look like for you? How does giving make you feel?",
      "Who in your life has a healthy relationship with money? What can you learn from them?",
      "What financial goal feels both exciting and achievable in the next year?",
      "What money habits would you like to build? What habits need to go?",
      "Write a letter to money itself. What do you want to say?",
      "What would financial peace feel like? Describe it in detail.",
      "Create a positive money affirmation that feels true for you.",
      "What's one money mindset shift you're committing to? How will you practice it?",
    ],
  },

  // ===== NEW RELATIONSHIPS PROGRAMS =====
  {
    id: 'finding-love',
    name: 'Finding Love',
    description: 'Prepare your heart for meaningful partnership',
    icon: '💕',
    color: 'bg-rose-50 border-rose-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      "What does love mean to you? How has your definition evolved over time?",
      "Describe your ideal partner. Not just looks—who are they as a person?",
      "What are your non-negotiables in a relationship? What are your nice-to-haves?",
      "Write about your relationship history. What patterns do you notice?",
      "What did your parents' relationship teach you about love?",
      "What are you still carrying from past relationships that you need to release?",
      "What do you bring to a relationship? What makes you a great partner?",
      "What parts of yourself are you still working on before partnership?",
      "What's your attachment style? How does it show up in relationships?",
      "Describe the life you want to build with a partner. What does it look like day-to-day?",
      "What fears do you have about love and commitment?",
      "Write a letter to your future partner. What do you want them to know about you?",
      "How do you typically meet potential partners? Is that working? What could you try?",
      "What are your dating deal-breakers? What red flags will you not ignore?",
      "How do you show love? How do you like to receive it?",
      "What does healthy communication in a relationship look like to you?",
      "Write about the best relationship you've witnessed. What made it work?",
      "What would you need to change or adjust in your life to make room for love?",
      "How will you stay true to yourself while being open to partnership?",
      "What's your relationship with being alone? Are you comfortable with yourself?",
      "Write about the love you deserve. Claim it fully.",
    ],
  },
  {
    id: 'new-parent-year-one',
    name: 'New Parent: Year One',
    description: 'Document and process your first year as a parent',
    icon: '👶',
    color: 'bg-blue-50 border-blue-300',
    category: 'relationships',
    duration: 30,
    prompts: [
      "Write about the moment you became a parent. What did you feel?",
      "Describe your baby right now. What are they like? What do you notice about them?",
      "What has been the most surprising thing about parenthood so far?",
      "What has been harder than you expected? It's okay to be honest.",
      "What has been more joyful than you imagined?",
      "Write about a moment of pure love you've experienced with your baby.",
      "How has your relationship with your partner changed since becoming parents?",
      "What do you miss about your life before baby?",
      "What have you gained that you never could have imagined?",
      "Write about your baby's latest milestone or development. Capture this moment.",
      "What kind of parent do you want to be? What values do you want to instill?",
      "How are you taking care of yourself? What do you need more of?",
      "Write a letter to your baby about who you are right now as their parent.",
      "What support do you have? What support do you need?",
      "Describe a typical day right now. You'll want to remember this.",
      "What fears do you carry as a new parent? Name them.",
      "What makes your baby laugh? What soothes them?",
      "Write about the village around you. Who has shown up for your family?",
      "How has becoming a parent changed how you see your own parents?",
      "What traditions do you want to start with your child?",
      "Describe your baby's personality emerging. What traits do you see?",
      "What's something you've learned about yourself through parenthood?",
      "Write about a hard day. It's okay to document the struggle.",
      "Write about a perfect moment. A snapshot you want to remember forever.",
      "How has your identity shifted since becoming a parent?",
      "What do you hope your child's childhood feels like?",
      "Write a letter to yourself when you were expecting. What would you say?",
      "What does your baby need from you right now in this phase?",
      "What do you need from yourself right now?",
      "As year one closes, what do you want to remember most about this time?",
    ],
  },
  {
    id: 'empty-nest',
    name: 'Empty Nest',
    description: 'Navigate the transition as children leave home',
    icon: '🪺',
    color: 'bg-amber-50 border-amber-200',
    category: 'relationships',
    duration: 14,
    prompts: [
      "Describe this transition. How does the empty nest feel?",
      "What emotions are you experiencing? There may be many—name them all.",
      "What do you miss most about having your children at home?",
      "What are you relieved about, even if it feels hard to admit?",
      "Write about your identity beyond being a parent. Who else are you?",
      "What parts of yourself did you set aside during active parenting that you can reclaim?",
      "How is your relationship with your partner (if applicable) shifting?",
      "What will you do with this new time and space?",
      "Write about the parent you were. What are you proud of?",
      "What do you hope your children carry forward from their childhood?",
      "How will you stay connected to your adult children without overstepping?",
      "Write a letter to your child as they begin their independent life.",
      "What does this new chapter of your life look like? Dream big.",
      "What will you do differently now that you have this freedom?",
    ],
  },
  {
    id: 'divorce-recovery',
    name: 'Divorce Recovery',
    description: 'Heal, process, and reimagine your life after divorce',
    icon: '🌱',
    color: 'bg-teal-50 border-teal-300',
    category: 'relationships',
    duration: 21,
    prompts: [
      "Write about where you are right now. How are you feeling in this moment?",
      "What led to the end of your marriage? Tell the story honestly.",
      "What emotions are you cycling through? Anger, grief, relief, fear? All are valid.",
      "What did you love about your relationship? It's okay to honor what was good.",
      "What patterns or dynamics didn't work? What can you learn for the future?",
      "What's your role in what happened? Taking ownership can be healing.",
      "What are you grieving? The person, the dream, the life you planned?",
      "Write a letter you'll never send to your ex. Say everything you need to say.",
      "How are you taking care of yourself right now? What do you need more of?",
      "What support system do you have? Who has shown up for you?",
      "If you have children, how are you navigating co-parenting? What's working?",
      "What does your daily life look like now? Describe your new normal.",
      "What parts of yourself did you lose in the marriage that you want to reclaim?",
      "Write about something good that has come from this difficult experience.",
      "What are you learning about yourself through this process?",
      "What do you want your life to look like one year from now?",
      "What kind of partner do you want to be in the future, if you choose partnership again?",
      "What boundaries do you need to set to protect your healing?",
      "Write a letter of forgiveness—to yourself, to your ex, or to the situation.",
      "What has this experience taught you about love, relationships, and yourself?",
      "Write about the person you're becoming. What's emerging from this cocoon?",
    ],
  },

  // ===== CREATIVITY PROGRAMS =====
  {
    id: 'writers-journal',
    name: "Writer's Journal",
    description: 'Daily prompts to nurture your writing practice',
    icon: '✍️',
    color: 'bg-violet-50 border-violet-300',
    category: 'creativity',
    duration: 30,
    prompts: [
      "What kind of writer do you want to be? What stories are you meant to tell?",
      "Write about your earliest memory of loving words—reading or writing.",
      "Describe a character who won't leave your imagination. Who are they?",
      "What's a story idea you've been carrying that wants to be written?",
      "Write the opening paragraph of something—anything. Just begin.",
      "What writers do you admire? What do you want to learn from them?",
      "Describe a setting from your life that would make a great story location.",
      "What's the hardest part of writing for you? What blocks you?",
      "Write a piece of dialogue between two characters. Let them surprise you.",
      "What themes keep appearing in your writing or ideas? What are you drawn to?",
      "Describe an ordinary moment in extraordinary detail. Make the mundane magical.",
      "What would you write if no one would ever read it?",
      "Write about a strong emotion you've felt recently. Use all five senses.",
      "Create a character based on someone you observed today. Imagine their inner life.",
      "What's a story from your family history that deserves to be told?",
      "Write the worst first draft of something. Give yourself permission to write badly.",
      "What time of day do you write best? How can you protect that time?",
      "Describe a conflict—internal or external. How might it resolve?",
      "Write a letter from one character to another.",
      "What would your writing space look like in your ideal life?",
      "Write about a place from your childhood as if you're there right now.",
      "What's a book you wish existed? Maybe you're meant to write it.",
      "Write about transformation—a character, a place, or yourself as a writer.",
      "Describe the last time you felt fully alive. Mine that feeling for your work.",
      "What's your writing ritual? What helps you get into the flow?",
      "Write an ending. Any ending. See where it takes you.",
      "What have you learned about yourself as a writer during this program?",
      "Write about what you're afraid to write about. Edge toward it.",
      "What's one writing goal for the next month? Make it specific.",
      "Write a message to yourself for the days when writing feels impossible.",
    ],
  },
  {
    id: 'unlock-creativity',
    name: 'Unlock Your Creativity',
    description: 'Break through blocks and reconnect with your creative self',
    icon: '🎨',
    color: 'bg-fuchsia-50 border-fuchsia-300',
    category: 'creativity',
    duration: 21,
    prompts: [
      "What does creativity mean to you? How do you express it?",
      "When did you feel most creative as a child? What were you doing?",
      "What happened to that creative child? Write about when and why you stopped creating.",
      "What messages did you receive about creativity and artists? Were they supportive or limiting?",
      "What creative dreams have you abandoned? Why did you let them go?",
      "What would you create if you knew you couldn't fail?",
      "Describe your inner critic's voice. What does it say about your creativity?",
      "Write a response to your inner critic from your creative self.",
      "What conditions do you need to be creative? Time, space, materials, mood?",
      "Try something creative today—anything. Write about the experience.",
      "Who in your life supports your creativity? Who dampens it?",
      "What does a creative life look like to you? Describe it in detail.",
      "What's a creative skill you'd like to develop? How might you start?",
      "Write about a creative work (any medium) that deeply moved you. Why?",
      "What's blocking your creativity right now? Fear? Time? Perfectionism? Something else?",
      "For each block, write one small way you could work around it.",
      "Describe your ideal creative practice. How often? What medium? What does it feel like?",
      "Make something imperfect today on purpose. Write about releasing perfectionism.",
      "What would you create if you had a whole day devoted to making?",
      "How might your life change if you prioritized creativity?",
      "Write a commitment to your creative self. What will you do to nurture this part of you?",
    ],
  },
];

// Get program progress from localStorage
export function getProgramProgress(programId: string): { startDate: string | null; currentDay: number } {
  if (typeof window === 'undefined') {
    return { startDate: null, currentDay: 0 };
  }

  const key = `program_${programId}`;
  const stored = localStorage.getItem(key);

  if (!stored) {
    return { startDate: null, currentDay: 0 };
  }

  const { startDate } = JSON.parse(stored);
  const start = new Date(startDate);
  const now = new Date();
  const diffTime = Math.abs(now.getTime() - start.getTime());
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));

  return { startDate, currentDay: diffDays + 1 };
}

// Start a program
export function startProgram(programId: string): void {
  if (typeof window === 'undefined') return;

  const key = `program_${programId}`;
  localStorage.setItem(key, JSON.stringify({
    startDate: new Date().toISOString(),
  }));
}

// Reset a program
export function resetProgram(programId: string): void {
  if (typeof window === 'undefined') return;

  const key = `program_${programId}`;
  localStorage.removeItem(key);
}

// Get programs by category
export function getProgramsByCategory(category: ProgramCategory): GuidedProgram[] {
  return guidedPrograms.filter(p => p.category === category);
}
