export interface Quote {
  text: string;
  author: string;
}

export const inspiringQuotes: Quote[] = [
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The pen is mightier than the sword.", author: "Edward Bulwer-Lytton" },
  { text: "Fill your paper with the breathings of your heart.", author: "William Wordsworth" },
  { text: "Start writing, no matter what. The water does not flow until the faucet is turned on.", author: "Louis L'Amour" },
  { text: "There is no greater agony than bearing an untold story inside you.", author: "Maya Angelou" },
  { text: "Writing is the painting of the voice.", author: "Voltaire" },
  { text: "A writer is someone for whom writing is more difficult than it is for other people.", author: "Thomas Mann" },
  { text: "The first draft is just you telling yourself the story.", author: "Terry Pratchett" },
  { text: "You can always edit a bad page. You can't edit a blank page.", author: "Jodi Picoult" },
  { text: "Write what should not be forgotten.", author: "Isabel Allende" },
  { text: "The scariest moment is always just before you start.", author: "Stephen King" },
  { text: "If you want to be a writer, you must do two things above all others: read a lot and write a lot.", author: "Stephen King" },
  { text: "Writing is an exploration. You start from nothing and learn as you go.", author: "E.L. Doctorow" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "You don't start out writing good stuff. You start out writing crap and thinking it's good stuff, and then gradually you get better at it.", author: "Octavia Butler" },
  { text: "We write to taste life twice, in the moment and in retrospect.", author: "Anais Nin" },
  { text: "Journal writing is a voyage to the interior.", author: "Christina Baldwin" },
  { text: "Keeping a journal of what's going on in your life is a good way to help you distill what's important and what's not.", author: "Martina Navratilova" },
  { text: "Journaling is like whispering to one's self and listening at the same time.", author: "Mina Murray" },
  { text: "The habit of writing for my own eye is good practice. It loosens the ligaments.", author: "Virginia Woolf" },
  { text: "In the journal I do not just express myself more openly than I could to any person; I create myself.", author: "Susan Sontag" },
  { text: "I can shake off everything as I write; my sorrows disappear, my courage is reborn.", author: "Anne Frank" },
  { text: "Your journal is your private place to express your most authentic self.", author: "Unknown" },
  { text: "Writing in a journal reminds you of your goals and of your learning in life.", author: "Robin Sharma" },
  { text: "The life of every man is a diary in which he means to write one story, and writes another.", author: "James Matthew Barrie" },
  { text: "Journaling helps you to become a better writer and gives you a living record of your life.", author: "Michael Hyatt" },
  { text: "One day I will find the right words, and they will be simple.", author: "Jack Kerouac" },
  { text: "Words are a lens to focus one's mind.", author: "Ayn Rand" },
  { text: "The beautiful part of writing is that you don't have to get it right the first time.", author: "Robert Cormier" },
  { text: "Writing is thinking on paper.", author: "William Zinsser" },
  { text: "Your intuition knows what to write, so get out of the way.", author: "Ray Bradbury" },
  { text: "The desire to write grows with writing.", author: "Erasmus" },
  { text: "Either write something worth reading or do something worth writing.", author: "Benjamin Franklin" },
  { text: "I write entirely to find out what I'm thinking.", author: "Joan Didion" },
  { text: "The pages are still blank, but there is a miraculous feeling of the words being there.", author: "Vladimir Nabokov" },
  { text: "You must stay drunk on writing so reality cannot destroy you.", author: "Ray Bradbury" },
  { text: "Almost all good writing begins with terrible first efforts.", author: "Anne Lamott" },
  { text: "Write hard and clear about what hurts.", author: "Ernest Hemingway" },
  { text: "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", author: "Virginia Woolf" },
  { text: "Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.", author: "Ralph Waldo Emerson" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { text: "What we think, we become.", author: "Buddha" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Gratitude turns what we have into enough.", author: "Anonymous" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Get busy living or get busy dying.", author: "Stephen King" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { text: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { text: "You learn more from failure than from success. Don't let it stop you. Failure builds character.", author: "Unknown" },
  { text: "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.", author: "Steve Jobs" },
  { text: "People who are crazy enough to think they can change the world are the ones who do.", author: "Rob Siltanen" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
  { text: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
  { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { text: "Logic will get you from A to Z; imagination will get you everywhere.", author: "Albert Einstein" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller" },
  { text: "It is not the length of life, but depth of life.", author: "Ralph Waldo Emerson" },
  { text: "Find out who you are and be that person. That's what your soul was put on this Earth to be.", author: "Ellen DeGeneres" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", author: "Rumi" },
  { text: "Don't be satisfied with stories, how things have gone with others. Unfold your own myth.", author: "Rumi" },
  { text: "You were born with wings, why prefer to crawl through life?", author: "Rumi" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass" },
  { text: "Be where you are, not where you think you should be.", author: "Unknown" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
];

// Get quote by day of year for consistency
export function getDailyQuote(): Quote {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  return inspiringQuotes[dayOfYear % inspiringQuotes.length];
}

// Get random quote
export function getRandomQuote(): Quote {
  return inspiringQuotes[Math.floor(Math.random() * inspiringQuotes.length)];
}
